#datasource
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/.fame/db/fame
    username: root
    password: root
  h2:
    console:
      settings:
        web-allow-others: false
      path: /h2-console
      enabled: false

  jpa:
    show-sql: false
#log
logging:
  level:
    root: INFO
    org:
      springframework:
        web: INFO
  file:
    name: log/fame.log